export const footballImages = [
    {
        image:require('../../assets/cover/beast.jpg')
    },
    {
        image:require('../../assets/cover/butler.jpg')
    },
    {
        image:require('../../assets/cover/catch.jpg')
    },
    {
        image:require('../../assets/cover/catch2.jpg')
    },
    {
        image:require('../../assets/cover/dorsett.jpg')
    },
    {
        image:require('../../assets/cover/edelman.jpg')
    },
    {
        image:require('../../assets/cover/ghost.jpg')
    },
    {
        image:require('../../assets/cover/gleason.jpg')
    },
    {
        image:require('../../assets/cover/harrison.jpg')
    },
    {
        image:require('../../assets/cover/Immaculate.jpg')
    },
    {
        image:require('../../assets/cover/meadowlands.jpg')
    },
    {
        image:require('../../assets/cover/miami.jpg')
    },
    {
        image:require('../../assets/cover/minneapolis.jpg')
    },
    {
        image:require('../../assets/cover/philly.jpg')
    },
    {
        image:require('../../assets/cover/rodgers.jpg')
    },
    {
        image:require('../../assets/cover/roller.jpg')
    },
    {
        image:require('../../assets/cover/swann.jpg')
    },
    {
        image:require('../../assets/cover/thomas.jpg')
    },
];

export default footballImages;